import { type NextPage } from "next";
import Head from "next/head";

import CenteredContainer from "@/components/ui/CenteredContainer";
import Input from "@/components/ui/Input";
import Paragraph from "@/components/ui/Paragraph";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CenteredContainer minHeight="screen" className="flex-col gap-4">
        <Paragraph size="4xl" className="text-center">
          Tired of homeworks? <br /> Embrace the{" "}
          <span className="text-pink-300">power</span> of AI🧠
        </Paragraph>
        <Input variant="neutral" size="md" />
      </CenteredContainer>
    </>
  );
};

export default Home;
